ValueSet: CDHIv1
Title: "Classification of Digital Health Interventions v1"
Description:  "Value Set for Classification of Digital Health Interventions v1. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = true
* include codes from system CDHIv1

