ValueSet: CDSCv1
Title: "Classification of Digital Health System Categories v1"
Description:  "Value Set for Classification of Digital Health System Categories v1. Autogenerated from DAK artifacts"
* ^status = #active
* ^experimental = true
* include codes from system CDSCv1

