#!/usr/bin/env python3


resources = { 'codesystems' : {} , 'valuesets' : {}  }

def save_resources(resources,directory):
    for id,resource in resources.items() :
        try:
            file = open("input/fsh/" + directory + "/" + id + ".fsh","w")
            print(resource,file=file)
            file.close()
        except IOError as e:
            print("Could not save resource of type: " + directory + "  with id: " + id + "\n")
            print(f"\tError: {e}")


def generate_cs_and_vs_from_dict(id:str, title:str, dict:dict, resources:dict):
    if len(dict) == 0:
        return False
    
    codesystem = 'CodeSystem: ' + escape(id) + '\n'
    codesystem += 'Title: "' + escape(title) + '"\n'
    codesystem += 'Description:  "CodeSystem for ' + escape(title) + '. Autogenerated from DAK artifacts"\n'
    codesystem += '* ^experimental = true\n'
    codesystem += '* ^caseSensitive = false\n'
    codesystem += '* ^status = #active\n'
    for code,name in dict.items():
        codesystem += '* #' + escape(code) +  ' "' + escape(name) + '"\n'
        
    valueset = 'ValueSet: ' + escape(id) + '\n'
    valueset += 'Title: "' + escape(title) + '"\n'
    valueset += 'Description:  "Value Set for ' + escape(title) + '. Autogenerated from DAK artifacts"\n'
    valueset += '* ^status = #active\n'
    valueset += '* ^experimental = true\n'
    valueset += '* include codes from system ' + escape(id) + '\n'
    

    resources['codesystems'][id] = codesystem
    resources['valuesets'][id] = valueset

    return True

def escape(input):
    if ( not (isinstance(input,str))):
        return None
    return input.replace('"', r'\"')


print ("System Categories")
interventions = {}
for line in open('input/data/system_categories.txt', 'r'):
    parts = line.strip().split(' ',1)
    if (len(parts) < 2):
        continue
    code = parts[0].strip().rstrip(".")
    intervention = parts[1].strip()
    print ("\t" + intervention + ' = ' + code)
    interventions[code] = intervention    
generate_cs_and_vs_from_dict('CDSCv1', 'Classification of Digital Health System Categories v1', interventions, resources)


print ("Interventions")
interventions = {}
for line in open('input/data/dhi_v1.txt', 'r'):
    parts = line.strip().split(' ',1)
    if (len(parts) < 2):
        continue
    codes = parts[0].strip().split('.')
    code = ".".join(codes)
    intervention = parts[1].strip()
    print ("\t" + intervention + ' = ' + code)
    interventions[code] = intervention    
generate_cs_and_vs_from_dict('CDHIv1', 'Classification of Digital Health Interventions v1', interventions, resources)



for directory, instances in resources.items() :
    save_resources(instances,directory)


    
    
